# Database credentials
database:
  # antingen denna
  file: "db.sqlite" 
  # eller alla dessa (om file är blankt)
  sql-user: ""            #
  sql-pass: ""
  sql-server: "127.0.0.1"
  sql-database: "SupportSystem"
  sql-port: 3306

redis:
  server: "myredisserver1:6379"




